version: '3.8'

services:
  db:
    image: postgres:17.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:\dockers\pg
volumes:

  postgres_data: