create table region(id      int generated by default as identity primary key
                ,   code    varchar(50) not null unique
                );

create table city(  id 			int generated by default as identity primary key
                ,	code        varchar(50) not null unique
                ,	name_rus    varchar(255) not null
                ,   name_eng    varchar(255) not null
                ,   population  int
                ,   region      int references region(id)
                );

