create database client_db;

use database client_db;

create table client(id 			int 			generated by default as identity primary key
				,	full_name 	varchar(255)	not null
				,	inn 		varchar(12)
				);

create table reg_doc_type(	id 			int				generated by default as identity primary key
						,	doc_code	varchar(10)		not null unique
						,	doc_name	varchar(255)	not null
						);


create table client_reg_doc(	id			int generated by default as identity primary key
							,	client_id	int	references client(id)
							,	doc_type	int	references reg_doc_type(id)
							,	ser			varchar(255)	not null
							,	num			varchar(255) 	not null
							,	description	varchar(255) 	not null
							);


